-- MySQL Script generated by MySQL Workbench
-- 09/02/20 13:04:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hawo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hawo` ;

-- -----------------------------------------------------
-- Schema hawo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hawo` DEFAULT CHARACTER SET utf8 ;
USE `hawo` ;

-- -----------------------------------------------------
-- Table `hawo`.`photoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`photoList` ;

CREATE TABLE IF NOT EXISTS `hawo`.`photoList` (
  `pid` INT NOT NULL,
  `photoName` VARCHAR(45) NULL,
  `photoLocation` VARCHAR(45) NULL,
  `photoSrc` BLOB NULL,
  `uid` INT NULL,
  `photoListcol` VARCHAR(45) NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`pid`),
  UNIQUE INDEX `pid_UNIQUE` (`pid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hawo`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`article` ;

CREATE TABLE IF NOT EXISTS `hawo`.`article` (
  `aid` INT NOT NULL,
  `photoName` VARCHAR(45) NULL,
  `Title` VARCHAR(20) NULL,
  `content` TEXT(200) NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`aid`),
  UNIQUE INDEX `pid_UNIQUE` (`aid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hawo`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`media` ;

CREATE TABLE IF NOT EXISTS `hawo`.`media` (
  `mid` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  `src` BLOB NULL,
  PRIMARY KEY (`mid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hawo`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`message` ;

CREATE TABLE IF NOT EXISTS `hawo`.`message` (
  `msid` INT NOT NULL,
  `fromid` INT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`msid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hawo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`user` ;

CREATE TABLE IF NOT EXISTS `hawo`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  `sex` ENUM('男', '女') NULL DEFAULT '男',
  `address` VARCHAR(45) NULL,
  `qq` INT(12) NULL,
  `github` VARCHAR(45) NULL,
  `freinds` VARCHAR(45) NULL,
  `photoList_pid` INT NOT NULL,
  `article_aid` INT NOT NULL,
  `media_mid` INT NOT NULL,
  `message_msid` INT NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `id_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_photoList1_idx` (`photoList_pid` ASC),
  INDEX `fk_user_article1_idx` (`article_aid` ASC),
  INDEX `fk_user_media1_idx` (`media_mid` ASC),
  INDEX `fk_user_message1_idx` (`message_msid` ASC),
  CONSTRAINT `fk_user_photoList1`
    FOREIGN KEY (`photoList_pid`)
    REFERENCES `hawo`.`photoList` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_article1`
    FOREIGN KEY (`article_aid`)
    REFERENCES `hawo`.`article` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_media1`
    FOREIGN KEY (`media_mid`)
    REFERENCES `hawo`.`media` (`mid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_message1`
    FOREIGN KEY (`message_msid`)
    REFERENCES `hawo`.`message` (`msid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hawo`.`freinds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`freinds` ;

CREATE TABLE IF NOT EXISTS `hawo`.`freinds` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hawo`.`user_has_photoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawo`.`user_has_photoList` ;

CREATE TABLE IF NOT EXISTS `hawo`.`user_has_photoList` (
  `user_uid` INT NOT NULL,
  `photoList_pid` INT NOT NULL,
  PRIMARY KEY (`user_uid`, `photoList_pid`),
  INDEX `fk_user_has_photoList_photoList1_idx` (`photoList_pid` ASC),
  INDEX `fk_user_has_photoList_user_idx` (`user_uid` ASC),
  CONSTRAINT `fk_user_has_photoList_user`
    FOREIGN KEY (`user_uid`)
    REFERENCES `hawo`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_photoList_photoList1`
    FOREIGN KEY (`photoList_pid`)
    REFERENCES `hawo`.`photoList` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
